name: terraform infa.

on:
  # workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  infrastructure:
    environment:
      name: 'infrastructure'
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: terraform init
        uses: robertdebock/terraform-action@1.1.4
        with:
          action: init
          directory: .
      - name: terraform validate
        uses: robertdebock/terraform-action@1.1.4
        with:
          action: validate
          directory: .
      - name: terraform plan
        uses: robertdebock/terraform-action@1.1.4
        with:
          action: plan
          directory: .
      - name: terraform apply
        uses: robertdebock/terraform-action@1.1.4
        with:
          action: apply
          directory: .
        env:
          TF_CLI_ARGS: "-input=false -auto-approve"
          
  post:
    environment:
      name: 'post'
    needs: [infrastructure]
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: terraform destroy
      uses: robertdebock/terraform-action@1.1.4
      with:
        action: destroy
        directory: .
      env:
        TF_CLI_ARGS: "-input=false -auto-approve"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
